### ISSUE TITLE
Getting off of afk

### ISSUE THREAD

**Issue by VinZar-gg** [2mal3/Advanced-AFK-Datapack#2]
The AFK detection works fine. However theres an issue when invulnerability is turned on. w
When coming back from afk-ing. it takes a minute or so until the effects disappear and the AFK status sets to off. Typing in chat and moving doesnt remove you from the AFK Status. maybe disable the effects of not being able to mine and move. Wouldnt it better when it allows you to mine and move and detecting that action will disable AFK status

**Comment by 2mal3** [comment]
Unfortunately, I could not reproduce the bug.

However, it would help me if you could answer the following questions:
- Which version of the datapack are you using?
- Is the datapack running on a server
- If yes, which server software is used (Bukkit, Spigot, PaperSpigot, Forge, Fabric)
- On which Minecraft version is the datapack running?
- Are you using any other datapacks and if so, which ones?

**Comment by 2mal3** [comment]
Closed due to inactivity
