### ISSUE TITLE
The delay before becoming AFK is inconsistent

### ISSUE THREAD

**Issue by Glaived** [2mal3/Advanced-AFK-Datapack#3]
1. Set a delay of 5min
2. Be on the move
3. Stop and start a stopwatch

You will pass AFK after a much shorter time than the 5min.

___

**Versions & details:**
- Server / ~~Local~~
- Minecraft `1.19.2`
- Fabric `v0.14.13`
- Advanced-AFK-Datapack `v2.1.0`

**Comment by 2mal3** [comment]
Oh yes, I can't do math properly. In the code, one minute corresponds to 10 seconds, which is wrong, of course. Thank you!
